# Used by "mix format"
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  # Pre-generated by `mix protox.generate` from protos/*.proto.
  # Regenerate with `mix longbridge.gen_protos` (see mix.exs aliases).
  ignore_files: ["lib/longbridge/_protos.ex"]
]
