[
  layers: [
    core: "Longbridge.*",
    adapters: "Longbridge.Adapters.*"
  ],
  deps: [
    forbidden: []
  ],
  source: [
    forbidden_modules: [],
    forbidden_files: []
  ],
  calls: [
    forbidden: []
  ],
  smells: [
    # _protos.ex is generated by protox — its repeated map shapes and
    # identical callback groups are generator output, not hand-written
    # code worth refactoring.
    fixed_shape_map: [
      ignore: [
        paths: ["lib/longbridge/_protos.ex"]
      ]
    ],
    behaviour_candidate: [
      ignore: [
        paths: ["lib/longbridge/_protos.ex"]
      ]
    ]
  ]
]
