[
  layers: [
    core: "Longbridge.*",
    adapters: "Longbridge.Adapters.*"
  ],
  deps: [
    forbidden: []
  ],
  source: [
    forbidden_modules: [],
    forbidden_files: []
  ],
  calls: [
    forbidden: []
  ],
  smells: [
    # _protos.ex is generated by protox: repeated map shapes, identical
    # callback groups and one bare rescue per field are generator output,
    # not hand-written code worth refactoring. `ignore` is the global
    # smell filter (reach applies it in addition to each check's own
    # `ignore`), so this covers every smell check, not just
    # fixed_shape_map and behaviour_candidate.
    #
    # The "Protox.check_generator_version result unused" dead-code
    # findings on the same file cannot be silenced here: reach only
    # wires --baseline/checks.baseline to :arch and :smells, and the
    # dead-code check honours neither baselines nor `# reach:disable-*`
    # directives.
    ignore: [
      paths: ["lib/longbridge/_protos.ex"]
    ]
  ]
]
